//! Names of Nushell's built-in commands (generated from `help commands` in
//! Nushell 0.115.2). Used to resolve multi-word command names such as
//! `str trim` when the `builtin-commands` feature is enabled.

/// Every built-in command name, sorted.
pub static BUILTIN_COMMANDS: &[&str] = &[
    "abbr",
    "abbr list",
    "alias",
    "all",
    "ansi",
    "ansi gradient",
    "ansi link",
    "ansi strip",
    "any",
    "append",
    "ast",
    "attr",
    "attr category",
    "attr complete",
    "attr complete external",
    "attr deprecated",
    "attr example",
    "attr interactive",
    "attr search-terms",
    "banner",
    "biff",
    "biff span-balance",
    "biff span-fmt",
    "biff span-iso8601",
    "biff span-round",
    "biff span-since",
    "biff span-until",
    "biff tag-exec",
    "biff tag-files",
    "biff tag-lines",
    "biff tag-stat",
    "biff tag-untag",
    "biff time-add",
    "biff time-cmp",
    "biff time-fmt",
    "biff time-in",
    "biff time-of",
    "biff time-parse",
    "biff time-relative",
    "biff time-round",
    "biff time-seq",
    "biff time-sort",
    "biff tz-compatible",
    "biff tz-list",
    "bits",
    "bits and",
    "bits not",
    "bits or",
    "bits rol",
    "bits ror",
    "bits shl",
    "bits shr",
    "bits xor",
    "break",
    "bytes",
    "bytes add",
    "bytes at",
    "bytes build",
    "bytes collect",
    "bytes ends-with",
    "bytes index-of",
    "bytes length",
    "bytes remove",
    "bytes replace",
    "bytes reverse",
    "bytes split",
    "bytes starts-with",
    "cal",
    "cd",
    "char",
    "chunk-by",
    "chunks",
    "clear",
    "collect",
    "columns",
    "combinations",
    "commandline",
    "commandline complete",
    "commandline edit",
    "commandline get-cursor",
    "commandline set-cursor",
    "commandline set-prompt",
    "compact",
    "complete",
    "config",
    "config env",
    "config flatten",
    "config nu",
    "config reset",
    "config use-colors",
    "const",
    "continue",
    "cp",
    "date",
    "date format",
    "date from-human",
    "date humanize",
    "date list-timezone",
    "date now",
    "date to-timezone",
    "debug",
    "debug env",
    "debug experimental-options",
    "debug info",
    "debug profile",
    "decode",
    "decode base32",
    "decode base32hex",
    "decode base64",
    "decode hex",
    "def",
    "default",
    "describe",
    "detect",
    "detect columns",
    "detect type",
    "df",
    "df aggregate",
    "df cast",
    "df collect",
    "df count",
    "df describe",
    "df distinct",
    "df drop",
    "df explain",
    "df filter",
    "df from-nu",
    "df join",
    "df limit",
    "df open",
    "df register",
    "df rename",
    "df sample",
    "df save",
    "df schema",
    "df select",
    "df sort",
    "df sql",
    "df tables",
    "df union",
    "df unregister",
    "df with-column",
    "difference",
    "do",
    "drop",
    "drop column",
    "drop nth",
    "dt",
    "dt add",
    "dt diff",
    "dt format",
    "dt now",
    "dt part",
    "dt to",
    "dt utcnow",
    "du",
    "each",
    "each while",
    "echo",
    "emoji",
    "encode",
    "encode base32",
    "encode base32hex",
    "encode base64",
    "encode hex",
    "enumerate",
    "error",
    "error make",
    "every",
    "exec",
    "exit",
    "exp",
    "explain",
    "explore",
    "explore config",
    "explore regex",
    "export",
    "export alias",
    "export const",
    "export def",
    "export extern",
    "export module",
    "export use",
    "export-env",
    "extern",
    "file",
    "fill",
    "filter",
    "find",
    "first",
    "flatten",
    "for",
    "format",
    "format bits",
    "format date",
    "format duration",
    "format filesize",
    "format number",
    "format pattern",
    "from",
    "from csv",
    "from eml",
    "from ics",
    "from ini",
    "from json",
    "from kdl",
    "from md",
    "from msgpack",
    "from msgpackz",
    "from nuon",
    "from ods",
    "from parquet",
    "from plist",
    "from ssv",
    "from toml",
    "from toon",
    "from tsv",
    "from url",
    "from vcf",
    "from xlsx",
    "from xml",
    "from yaml",
    "from yml",
    "generate",
    "get",
    "glob",
    "grid",
    "group-by",
    "gstat",
    "hash",
    "hash md5",
    "hash sha256",
    "hash sha512",
    "headers",
    "help",
    "help aliases",
    "help commands",
    "help escapes",
    "help externs",
    "help modules",
    "help operators",
    "help pipe-and-redirect",
    "hide",
    "hide-env",
    "histogram",
    "history",
    "history import",
    "history session",
    "http",
    "http delete",
    "http get",
    "http head",
    "http options",
    "http patch",
    "http pool",
    "http post",
    "http put",
    "idx",
    "idx dirs",
    "idx drop",
    "idx files",
    "idx find",
    "idx init",
    "idx search",
    "idx status",
    "idx watch",
    "if",
    "ignore",
    "inc",
    "input",
    "input list",
    "input listen",
    "insert",
    "inspect",
    "interleave",
    "intersect",
    "into",
    "into binary",
    "into bool",
    "into cell-path",
    "into datetime",
    "into duration",
    "into filesize",
    "into float",
    "into glob",
    "into int",
    "into matrix",
    "into record",
    "into semver",
    "into semver-range",
    "into sqlite",
    "into string",
    "into value",
    "is-admin",
    "is-empty",
    "is-not-empty",
    "is-redirected",
    "is-terminal",
    "items",
    "job",
    "job describe",
    "job flush",
    "job id",
    "job kill",
    "job list",
    "job recv",
    "job send",
    "job spawn",
    "job unfreeze",
    "join",
    "json path",
    "jwalk",
    "keybindings",
    "keybindings default",
    "keybindings list",
    "keybindings listen",
    "kill",
    "last",
    "length",
    "let",
    "let-env",
    "lines",
    "load-env",
    "loop",
    "ls",
    "match",
    "math",
    "math abs",
    "math arccos",
    "math arccosh",
    "math arcsin",
    "math arcsinh",
    "math arctan",
    "math arctanh",
    "math avg",
    "math cbrt",
    "math ceil",
    "math cos",
    "math cosh",
    "math exp",
    "math floor",
    "math ln",
    "math log",
    "math max",
    "math median",
    "math min",
    "math mode",
    "math product",
    "math round",
    "math sin",
    "math sinh",
    "math sqrt",
    "math stddev",
    "math sum",
    "math tan",
    "math tanh",
    "math variance",
    "matrix",
    "matrix add",
    "matrix get-col",
    "matrix get-row",
    "matrix identity",
    "matrix into-nu",
    "matrix map",
    "matrix max",
    "matrix mean",
    "matrix multiply",
    "matrix reduce",
    "matrix reshape",
    "matrix scale",
    "matrix set-col",
    "matrix set-row",
    "matrix subtract",
    "matrix sum",
    "matrix transpose",
    "matrix zeros",
    "merge",
    "merge deep",
    "metadata",
    "metadata access",
    "metadata set",
    "mkdir",
    "mktemp",
    "module",
    "move",
    "mut",
    "mv",
    "nu-check",
    "nu-highlight",
    "open",
    "overlay",
    "overlay hide",
    "overlay list",
    "overlay new",
    "overlay use",
    "panic",
    "par-each",
    "parse",
    "path",
    "path basename",
    "path dirname",
    "path exists",
    "path expand",
    "path join",
    "path parse",
    "path relative-to",
    "path self",
    "path split",
    "path type",
    "peek",
    "permutations",
    "plugin",
    "plugin add",
    "plugin list",
    "plugin rm",
    "plugin stop",
    "plugin use",
    "polars",
    "polars agg",
    "polars agg-groups",
    "polars all-false",
    "polars all-true",
    "polars append",
    "polars arg-max",
    "polars arg-min",
    "polars arg-sort",
    "polars arg-true",
    "polars arg-unique",
    "polars arg-where",
    "polars as",
    "polars as-date",
    "polars as-datetime",
    "polars cache",
    "polars cast",
    "polars col",
    "polars collect",
    "polars columns",
    "polars concat",
    "polars concat-str",
    "polars contains",
    "polars convert-time-zone",
    "polars count",
    "polars count-null",
    "polars cumulative",
    "polars cut",
    "polars datepart",
    "polars decimal",
    "polars drop",
    "polars drop-duplicates",
    "polars drop-nulls",
    "polars dummies",
    "polars entropy",
    "polars explode",
    "polars expr-not",
    "polars fill-nan",
    "polars fill-null",
    "polars filter",
    "polars filter-with",
    "polars first",
    "polars flatten",
    "polars get",
    "polars get-day",
    "polars get-hour",
    "polars get-minute",
    "polars get-month",
    "polars get-nanosecond",
    "polars get-ordinal",
    "polars get-second",
    "polars get-week",
    "polars get-weekday",
    "polars get-year",
    "polars group-by",
    "polars horizontal",
    "polars implode",
    "polars integer",
    "polars into-df",
    "polars into-dtype",
    "polars into-lazy",
    "polars into-nu",
    "polars into-repr",
    "polars into-schema",
    "polars is-duplicated",
    "polars is-in",
    "polars is-not-null",
    "polars is-null",
    "polars is-unique",
    "polars join",
    "polars join-where",
    "polars last",
    "polars len",
    "polars list-contains",
    "polars lit",
    "polars lowercase",
    "polars map-batches",
    "polars math",
    "polars math abs",
    "polars math bitwise-and",
    "polars math bitwise-count-ones",
    "polars math bitwise-count-zeros",
    "polars math bitwise-leading-ones",
    "polars math bitwise-leading-zeros",
    "polars math bitwise-or",
    "polars math bitwise-trailing-ones",
    "polars math bitwise-trailing-zeros",
    "polars math bitwise-xor",
    "polars math cos",
    "polars math dot",
    "polars math exp",
    "polars math log",
    "polars math log1p",
    "polars math sign",
    "polars math sin",
    "polars math sqrt",
    "polars max",
    "polars mean",
    "polars median",
    "polars min",
    "polars n-unique",
    "polars not",
    "polars open",
    "polars otherwise",
    "polars over",
    "polars pivot",
    "polars profile",
    "polars qcut",
    "polars quantile",
    "polars query",
    "polars rename",
    "polars replace",
    "polars replace-time-zone",
    "polars reverse",
    "polars rolling",
    "polars sample",
    "polars save",
    "polars schema",
    "polars select",
    "polars selector",
    "polars selector all",
    "polars selector alpha",
    "polars selector alphanumeric",
    "polars selector array",
    "polars selector binary",
    "polars selector boolean",
    "polars selector by-dtype",
    "polars selector by-index",
    "polars selector by-name",
    "polars selector categorical",
    "polars selector contains",
    "polars selector date",
    "polars selector datetime",
    "polars selector decimal",
    "polars selector digit",
    "polars selector duration",
    "polars selector empty",
    "polars selector ends-with",
    "polars selector enum",
    "polars selector exclude",
    "polars selector first",
    "polars selector float",
    "polars selector integer",
    "polars selector last",
    "polars selector list",
    "polars selector matches",
    "polars selector nested",
    "polars selector not",
    "polars selector numeric",
    "polars selector object",
    "polars selector signed-integer",
    "polars selector starts-with",
    "polars selector string",
    "polars selector struct",
    "polars selector temporal",
    "polars selector unsigned-integer",
    "polars set",
    "polars set-with-idx",
    "polars shape",
    "polars shift",
    "polars slice",
    "polars sort-by",
    "polars std",
    "polars store-get",
    "polars store-ls",
    "polars store-rm",
    "polars str-join",
    "polars str-lengths",
    "polars str-replace",
    "polars str-replace-all",
    "polars str-slice",
    "polars str-split",
    "polars str-strip-chars",
    "polars strftime",
    "polars struct-json-encode",
    "polars sum",
    "polars summary",
    "polars take",
    "polars truncate",
    "polars unique",
    "polars unnest",
    "polars unpivot",
    "polars uppercase",
    "polars value-counts",
    "polars var",
    "polars when",
    "polars with-column",
    "port",
    "prepend",
    "print",
    "ps",
    "pwd",
    "query",
    "query db",
    "query git",
    "query json",
    "query web",
    "query webpage-info",
    "query xml",
    "random",
    "random binary",
    "random bool",
    "random chars",
    "random float",
    "random int",
    "random pass",
    "random uuid",
    "reduce",
    "regex",
    "reject",
    "rename",
    "return",
    "reverse",
    "rm",
    "roll",
    "roll down",
    "roll left",
    "roll right",
    "roll up",
    "rotate",
    "run",
    "run-external",
    "run-internal",
    "save",
    "schema",
    "scope",
    "scope aliases",
    "scope commands",
    "scope engine-stats",
    "scope externs",
    "scope modules",
    "scope variables",
    "select",
    "semver",
    "semver bump",
    "seq",
    "seq char",
    "seq date",
    "shuffle",
    "skip",
    "skip until",
    "skip while",
    "sleep",
    "slice",
    "sort",
    "sort-by",
    "source",
    "source-env",
    "split",
    "split cell-path",
    "split chars",
    "split column",
    "split list",
    "split row",
    "split words",
    "start",
    "stor",
    "stor create",
    "stor delete",
    "stor export",
    "stor import",
    "stor insert",
    "stor open",
    "stor reset",
    "stor update",
    "str",
    "str after",
    "str align",
    "str before",
    "str between",
    "str camel-case",
    "str capitalize",
    "str common-prefix",
    "str compress",
    "str contains",
    "str decompress",
    "str dedent",
    "str deunicode",
    "str distance",
    "str downcase",
    "str ends-with",
    "str escape-regex",
    "str expand",
    "str increment",
    "str indent",
    "str index-of",
    "str join",
    "str kebab-case",
    "str length",
    "str lowercase",
    "str pascal-case",
    "str replace",
    "str reverse",
    "str screaming-snake-case",
    "str shl-quote",
    "str shl-split",
    "str similarity",
    "str slug",
    "str snake-case",
    "str starts-with",
    "str stats",
    "str substring",
    "str title-case",
    "str trim",
    "str truncate",
    "str unescape",
    "str upcase",
    "str uppercase",
    "str wrap",
    "sys",
    "sys cpu",
    "sys disks",
    "sys host",
    "sys mem",
    "sys net",
    "sys temp",
    "sys users",
    "table",
    "take",
    "take until",
    "take while",
    "tee",
    "term",
    "term query",
    "term size",
    "timeit",
    "to",
    "to csv",
    "to gui",
    "to html",
    "to json",
    "to kdl",
    "to md",
    "to msgpack",
    "to msgpackz",
    "to nuon",
    "to parquet",
    "to plist",
    "to text",
    "to toml",
    "to toon",
    "to tsv",
    "to txt",
    "to xml",
    "to yaml",
    "to yml",
    "touch",
    "transpose",
    "tree",
    "try",
    "tui",
    "tui bind",
    "tui box",
    "tui button",
    "tui debug",
    "tui label",
    "tui log",
    "tui menu",
    "tui preview",
    "tui progress",
    "tui run",
    "tui search",
    "tui select",
    "tui split",
    "tui tab",
    "tui table",
    "tui textbox",
    "tui tree",
    "tutor",
    "ulimit",
    "umask",
    "uname",
    "union",
    "uniq",
    "uniq-by",
    "unlet",
    "update",
    "update cells",
    "upsert",
    "url",
    "url build-query",
    "url decode",
    "url encode",
    "url join",
    "url parse",
    "url split-query",
    "use",
    "values",
    "version",
    "version check",
    "view",
    "view blocks",
    "view files",
    "view ir",
    "view source",
    "view span",
    "watch",
    "where",
    "which",
    "while",
    "whoami",
    "window",
    "with-env",
    "wrap",
    "zip",
];
